### ISSUE TITLE
Doc update regarding key cloak /auth/admin

### ISSUE THREAD

**Issue by garethahealy** [mposolda/keycloak-freeipa-docker#2]
The users provided didn't work. Had to use default admin/admin

Docs need updating to reflect.

**Comment by abstractj** [comment]
@garethahealy could you please file a jira https://issues.jboss.org/browse/KEYCLOAK?

@mposolda I think we can disable GH issues into this repo, otherwise issues get lost. WDYT?

**Comment by mposolda** [comment]
@abstractj +1 
I will disable issues. 

I hope that from long-term perspective, your keycloak-freeipa integration work will allow to remove/deprecate this docker image :)
